site_name: Project Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Reference: reference.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - autorefs
  - mermaid2
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tasklist
  - toc:
      permalink: true
docs_dir: docs
